language: cpp

cache:
  yarn: true
  ccache: true

matrix:
  include:
    - os: linux
      compiler: 'clang-5.0-debug'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-5.0
            - libboost-all-dev
            - ccache
            - libstdc++-5-dev
      env: CCOMPILER=clang-5.0 CXXCOMPILER=clang++-5.0 BUILD_TYPE=Debug
    - os: linux
      compiler: 'clang-5.0-release'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-5.0
            - libboost-all-dev
            - ccache
            - libstdc++-5-dev

      env: CCOMPILER=clang-5.0 CXXCOMPILER=clang++-5.0 BUILD_TYPE=Release

install:
    - export CC=${CCOMPILER} CXX=${CXXCOMPILER}
    - mkdir -p build
    - pushd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - cmake --build .
    - popd
    - pushd frontend
    - yarn
    - popd

script:
    - ./build/common_tests
    - ./build/ev_tests
    - ./build/server_tests
    - ./build/preprocessing_tests
