language: cpp

matrix:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

install:
    - mkdir -p build
    - pushd build
    - cmake ..
    - cmake --build .
    - popd

script:
    - ./build/common_tests
    - ./build/ev_tests
    - ./build/server_tests
    - ./build/preprocessing_tests
